name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Minimal steps to reproduce the behavior
      placeholder: |
        1. Create a session with...
        2. Call sample() with...
        3. Observe error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal Reproduction Code
      description: If applicable, provide minimal code that reproduces the issue
      render: rust
      placeholder: |
        use physjitter::{Session, Evidence};

        fn main() {
            // Your reproduction code here
        }

  - type: input
    id: version
    attributes:
      label: physjitter Version
      description: Output of `cargo pkgid physjitter` or version in Cargo.toml
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: rust-version
    attributes:
      label: Rust Version
      description: Output of `rustc --version`
      placeholder: "rustc 1.75.0 (82e1608df 2023-12-21)"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other (specify in additional context)
    validations:
      required: true

  - type: checkboxes
    id: features
    attributes:
      label: Enabled Features
      description: Which feature flags are enabled?
      options:
        - label: "default"
        - label: "hardware"
        - label: "rand"

  - type: dropdown
    id: environment
    attributes:
      label: Environment Type
      description: Where is the code running?
      options:
        - Native (bare metal)
        - Virtual Machine
        - Container (Docker, etc.)
        - WSL/WSL2
        - Other

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, logs, or screenshots
