name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is it related to a frustration?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: Proposed API (if applicable)
      description: If this involves API changes, sketch out the proposed interface
      render: rust
      placeholder: |
        // Example proposed API
        impl Session {
            pub fn new_feature(&self) -> Result<(), Error> {
                // ...
            }
        }

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change?
      description: Would this require a breaking change to the API?
      options:
        - "No"
        - "Yes"
        - "Unsure"
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to submit a PR for this feature

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, use cases, or references
