name: Security Vulnerability
description: Report a security vulnerability (for non-critical issues only)
labels: ["security", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Security Notice

        **For critical security vulnerabilities, please do NOT use this template.**

        Instead, please report critical vulnerabilities privately via:
        - GitHub Security Advisories (preferred)
        - Email to the maintainers

        See [SECURITY.md](https://github.com/writerslogic/physjitter/blob/main/SECURITY.md) for details.

        ---

        This template is for **low-severity** security issues that are safe to discuss publicly, such as:
        - Documentation improvements for security guidance
        - Minor hardening suggestions
        - Security-related feature requests

  - type: checkboxes
    id: severity-check
    attributes:
      label: Severity Confirmation
      description: Please confirm this is appropriate for public disclosure
      options:
        - label: This is a LOW severity issue that is safe to discuss publicly
          required: true
        - label: I have read SECURITY.md and understand the private disclosure process for critical issues
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Documentation improvement
        - Hardening suggestion
        - Dependency concern
        - Security feature request
        - Other (low severity)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the security concern or suggestion
    validations:
      required: true

  - type: textarea
    id: recommendation
    attributes:
      label: Recommendation
      description: What changes would you suggest?

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information
